---
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Copy nginx configuration for wordpress
  notify: restart nginx
  ansible.builtin.template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: insert firewalld rule for nginx
  ansible.posix.firewalld:
    port: "{{ nginx_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true

- name: mginx service state
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
